[package]
name = "rusty_robot"
version = "0.1.0"
authors = ["Ryan McGee <ramtech51@comcast.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gilrs = "0.7.4"
rppal = "0.11.3"